server:
  port: 90
  servlet:
    context-path: /
  #tomcat:
   # accept-count: 1000
   # threads:
   #   max: 1000
   # max-connections: 20000
  jetty:
    threads:
      max: 1000
      max-queue-capacity: 20000
    max-http-form-post-size: -1
    max-threads: 1000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_spm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/META-INF/resources/webjars/,classpath:/META-INF/static/,classpath:/static/
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  freemarker:
    suffix: .ff
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sinictek.restfulapi.model